### ISSUE TITLE
Excess method call

### ISSUE THREAD

**Issue by AndreiSerov** [ABashkirova/SE-Test#1]
It would looks better these way: `!false` 

https://github.com/ABashkirova/SE-Test/blob/6e1f30595818c4a59a902d9bd96875c99b2b5800/src/main/kotlin/xyz/sashenka/Utils.kt#L53

**Comment by ABashkirova** [comment]
Спорно. Это, безусловно, привычно относительно java. Но почему нет, если это [стандартная функция языка](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-boolean/index.html)?

**Comment by AndreiSerov** [comment]
> Спорно. Это, безусловно, привычно относительно java. Но почему нет, если это [стандартная функция языка](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-boolean/index.html)?

Вот если бы писалось нот в начале, то да, как в пайотоне: сразу понятно `not child`  - нет детей, будто бы текст читаешь, а так восклицательный знак семантически более явно смотрится
