### ISSUE TITLE
Just for monoline file 

### ISSUE THREAD

**Issue by AndreiSerov** [ABashkirova/SE-Test#2]
It wouldn't works with other control characters such as \n \r \t

https://github.com/ABashkirova/SE-Test/blob/6e1f30595818c4a59a902d9bd96875c99b2b5800/src/main/kotlin/xyz/sashenka/Utils.kt#L57-L61

**Comment by ABashkirova** [comment]
А на чем проверить? 
У меня работает:
<img width="918" alt="Снимок экрана 2020-02-29 в 20 32 13" src="https://user-images.githubusercontent.com/20269264/75608511-af8d8000-5b32-11ea-8dab-21644227c43c.png">

**Comment by AndreiSerov** [comment]
Да, верно. Того косяка нет. Однако, есть ошибки со знаками препинаниния "кощей" и "кощей," будет два разных слова, хотя по факту нет

![image](https://user-images.githubusercontent.com/57676155/75609412-e23b7680-5b3a-11ea-80d2-f941ad5f6284.png)

**Comment by AndreiSerov** [comment]
> А на чем проверить?
> У меня работает:
> <img alt="Снимок экрана 2020-02-29 в 20 32 13" width="918" src="https://user-images.githubusercontent.com/20269264/75608511-af8d8000-5b32-11ea-8dab-21644227c43c.png">

Это консоль в идее?! У меня прост с темками уже очень некрасиво идея сделала и пришлось убрать=(

**Comment by ABashkirova** [comment]
> Да, верно. Того косяка нет. Однако, есть ошибки со знаками препинаниния "кощей" и "кощей," будет два разных слова, хотя по факту нет
> 
> ![image](https://user-images.githubusercontent.com/57676155/75609412-e23b7680-5b3a-11ea-80d2-f941ad5f6284.png)

В задаче явно не сказано что именно считать словом. "bla bla" или "1 2 3" или ". , $" или "asdfg". Если говорить о словах, которые имеют лексическое значение как единица языка, то задача все-таки несколько усложняется :) 
Я посчитала словом — любую последовательность символов не содержащую невидимые символы. 

> > А на чем проверить?
> > У меня работает:
> > <img alt="Снимок экрана 2020-02-29 в 20 32 13" width="918" src="https://user-images.githubusercontent.com/20269264/75608511-af8d8000-5b32-11ea-8dab-21644227c43c.png">
> 
> Это консоль в идее?! У меня прост с темками уже очень некрасиво идея сделала и пришлось убрать=(

Это [oh my zsh](https://ohmyz.sh) + плагины + темы.
