### ISSUE TITLE
консистентность

### ISSUE THREAD

**Issue by kozlyakov-m** [ABashkirova/SE-Test#4]
в строке 55 exitProcess(status=1), а в строке 73 exitProcess(0)
надо определиться)

https://github.com/ABashkirova/SE-Test/blob/35b8f97cf096444e44bfbbe9f6eb8cc8547ce330/src/main/kotlin/xyz/sashenka/Utils.kt#L55

**Comment by ABashkirova** [comment]
👍🏼
